source "https://rubygems.org"

gem "jekyll-feed", group: :jekyll_plugins
gem "github-pages", group: :jekyll_plugins
gem "jekyll"
# uncomment to preview locally
# gem "dendron-jekyll", git: "https://github.com/dendronhq/dendron-jekyll/"