---
name: Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 07 11 * * *

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      # For explanation as to why we use `persist-credentials` & `fetch-depth` see:
      #   https://github.com/ad-m/github-push-action#example-workflow-file
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - name: Install packages
        run: npm install

      - name: Build site w/ dendron
        run: npx dendron buildSiteV2 --stage prod

      # `git diff-index --quiet HEAD` will return an exit code of 1 if there are
      #   changes staged. If there are changes, it commits them back to the repo.
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff-index --quiet HEAD \
            || git commit -m "Build site."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}